// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf8_qGNT7gq86fiL3WxdkCBymG2zaQRq4',
    appId: '1:1013615921405:web:ea8db3d83a14716cc7d694',
    messagingSenderId: '1013615921405',
    projectId: 'gorev-takip-81cc2',
    authDomain: 'gorev-takip-81cc2.firebaseapp.com',
    storageBucket: 'gorev-takip-81cc2.firebasestorage.app',
    measurementId: 'G-LJHZ6MS009',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-M40qNYxr-Uu6KjuSO0qidd8XyqlUnno',
    appId: '1:1013615921405:android:53fc468b327a0561c7d694',
    messagingSenderId: '1013615921405',
    projectId: 'gorev-takip-81cc2',
    storageBucket: 'gorev-takip-81cc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoThiJhZ2a3mq2T6Oj4SfiZIniGs2CwhM',
    appId: '1:1013615921405:ios:656c18aa1ac8d82bc7d694',
    messagingSenderId: '1013615921405',
    projectId: 'gorev-takip-81cc2',
    storageBucket: 'gorev-takip-81cc2.firebasestorage.app',
    iosBundleId: 'com.example.gorevTakibi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoThiJhZ2a3mq2T6Oj4SfiZIniGs2CwhM',
    appId: '1:1013615921405:ios:656c18aa1ac8d82bc7d694',
    messagingSenderId: '1013615921405',
    projectId: 'gorev-takip-81cc2',
    storageBucket: 'gorev-takip-81cc2.firebasestorage.app',
    iosBundleId: 'com.example.gorevTakibi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf8_qGNT7gq86fiL3WxdkCBymG2zaQRq4',
    appId: '1:1013615921405:web:7a823e50757ee727c7d694',
    messagingSenderId: '1013615921405',
    projectId: 'gorev-takip-81cc2',
    authDomain: 'gorev-takip-81cc2.firebaseapp.com',
    storageBucket: 'gorev-takip-81cc2.firebasestorage.app',
    measurementId: 'G-XYGRPNN8C0',
  );
}
